apiVersion: controlplane.cluster.x-k8s.io/v1beta2
kind: AWSManagedControlPlane
metadata:
  labels:
    {{- include "capieks.labels" . | nindent 4 }}
  name: controlplane
spec:
  addons:
    {{- range $addon := .Values.cluster.addons }}
    - name: {{ $addon.name }}
      version: {{ $addon.version }}
      conflictResolution: "overwrite"
    {{- end }}
  associateOIDCProvider: true
  encryptionConfig:
    provider: {{ .Values.cluster.kms_key_arn }}
    resources:
      - "secrets"
  endpointAccess:
    private: true
    public: true
  iamAuthenticatorConfig:
    mapRoles:
      - username: {{ regexFind "[^/]+$" .Values.cluster.admin_role_arn | quote }}
        rolearn: {{ .Values.cluster.admin_role_arn | quote }}
        groups:
          - "system:masters"
  region: {{ .Values.cluster.region }}
  version: {{ .Values.cluster.version }}
  roleName: eks-controlplane.cluster-api-provider-aws.sigs.k8s.io
  sshKeyName: {{ .Values.cluster.ssh_key_name }}
