apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 00-main
  namespace: argocd
spec:
  destination:
    namespace: argocd
    name: in-cluster
  project: capi
  source:
    helm:
      valueFiles:
      - ../../values/values.yaml
    path: charts/00-main
    repoURL: https://github.com/dcoppa/capi.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - FailOnSharedResource=true
