apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Chart.Name }}-role
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - ""
  resourceNames:
  - "{{ .Values.cluster.name }}-cluster"
  resources:
  - secrets
  verbs:
  - delete
  - get
