apiVersion: batch/v1
kind: Job
metadata:
  name: argocd-cluster
  namespace: {{ .Release.Namespace }}
spec:
  template:
    metadata:
      labels:
        job: argocd-cluster
    spec:
      containers:
        - name: kubectl-dash
          image: docker.io/dcoppa/kubectl-dash:v1.32.1
          imagePullPolicy: IfNotPresent
          command: ['dash', '-c', "until kubectl -n {{ .Values.cluster.name }} get secrets {{ .Values.cluster.name }}-kubeconfig ; do sleep 1 ; done"]
      restartPolicy: OnFailure
      serviceAccountName: {{ .Release.Name }}-sa
  ttlSecondsAfterFinished: 1800
