gitrepo: https://github.com/dcoppa/capi.git
gitbranch: main
project: capi
apps:
  - name: 01-eks
    server: in-cluster
    order: 0
  - name: 02-external-secrets
    namespace: external-secrets
    order: 1
  - name: 03-nginx
    namespace: nginx
    order: 2
