apiVersion: controlplane.cluster.x-k8s.io/v1beta2
kind: AWSManagedControlPlane
metadata:
  labels:
    {{- include "capieks.labels" . | nindent 4 }}
  name: {{ .Values.cluster.name }}-control-plane
spec:
  addons:
    - name: "aws-ebs-csi-driver"
      version: "v1.35.0-eksbuild.1"
      conflictResolution: "overwrite"
  bastion:
    enabled: true
  endpointAccess:
    private: true
    public: false
  iamAuthenticatorConfig:
    mapRoles:
      - username: "kubernetes-admin"
        rolearn: {{ .Values.cluster.admin_role_arn | quote }}
        groups:
          - "system:masters"
  region: {{ .Values.cluster.region }}
  sshKeyName: {{ .Values.cluster.ssh_key_name }}
